### ISSUE TITLE
readme needs an update

### ISSUE THREAD

**Issue by dootMaster** [ianprime0509/pitchy#100]
Can't create instances of PitchDetector from static helper methods. Able to create new instance from PitchDetector by itself. 

After creating a new instance, asks for an FFT size and a buffer supplier. What is the buffer supplier?

**Comment by ianprime0509** [comment]
Could you expand on what problem you're having with the static helper methods? This is the intended way to get a `PitchDetector`:

```js
import { PitchDetector } from "pitchy";

const detector = PitchDetector.forFloat32Array(2048); /* substitute the appropriate input size */
```

All the static helper methods invoke the constructor, which isn't really intended to be used directly. The buffer supplier is just a function which takes an array length and constructs an array of the appropriate type: this is needed because several input types are supported (`number[]`, `Float32Array`, `Float64Array`), and internally it is best to have buffers be of the same type as the input data, for precision and efficiency reasons. So if you're going to provide input data as a `Float32Array`, you would use `PitchDetector.forFloat32Array`, for example.

To illustrate, this is what the `forFloat32Array` method does:
```js
  static forFloat32Array(inputLength) {
    return new PitchDetector(inputLength, (length) => new Float32Array(length));
  }
```
The `(length) => new Float32Array(length)` is the buffer supplier, so whenever an internal array is needed, the function is invoked with the desired length, as in this example from the `Autocorrelator` constructor:
```js
this._paddedInputBuffer = this._bufferSupplier(this._fft.size);
```

**Comment by dootMaster** [comment]
I'm unable to create an instance of PitchDetector via the forFloat32Array() method the way you've shown. If it works for you, I can only guess something on my end isn't working. I'm using a new bundler that might be doing something wonky. I've since then gotten another pitch detection package to work but thanks show me what syntax to try.

**Comment by ianprime0509** [comment]
Thanks for your feedback! I'm glad you found a solution that works for you. My best guess would be that maybe the setup you were using isn't compatible with ES modules, and since v4, Pitchy is a [pure ES module](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). Hopefully as the ecosystem continues to move towards ES modules, issues related to them will become less common, but admittedly, it can be somewhat painful with certain tools.
