### ISSUE TITLE
How do you configure the resolution?

### ISSUE THREAD

**Issue by ephetic** [ianprime0509/pitchy#11]
Right now its seems like the resolution is about 28 cents.  I've tried changing the analyzer node FFT size to no effect.

**Comment by ianprime0509** [comment]
What kind of input are you providing? The test suite checks the behavior against various waveforms at various pitches and amplitudes, although perhaps it should be asserting the accuracy in terms of cents rather than (or in addition to) percent error as it's doing now. Aside from that, I'm currently using the library in [Temperatune](https://github.com/ianprime0509/temperatune), where I have the "in tune" message displayed when the detected pitch is within 5 cents of the desired pitch, and it works within those parameters for tuning my viola.

I might want to create another example page where various properties can be configured so it's easier to experiment with the effects of making various changes (such as `fftSize`). Admittedly, I'm not an audio engineer by any means, so it's entirely possible that there are additional techniques that I could try to improve the accuracy or reliability of the pitch detection (some kind of smoothing, perhaps, to help with more irregular inputs; [the paper describing the algorithm](http://www.cs.otago.ac.nz/tartini/papers/A_Smarter_Way_to_Find_Pitch.pdf) mentions that they use a 75% overlap in windows when analyzing, which might be something worth trying). I noticed there's also a [`smoothingTimeConstant`](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/smoothingTimeConstant) property of `AnalyzerNode`, which might also be worth experimenting with.

**Comment by ephetic** [comment]
My 28c figure came from testing playing a note on harmonica into the laptop mic and then bending it down while logging the detected pitch.  it didn't register any change in frequency until it hit about 28c even tho my (lousy) ears could hear it bending.  I'll create gist of it this weekend to make sure it wasn't something in my application code.  thanks!

**Comment by ephetic** [comment]
Okay, so playing with the tests, it looks like it has a small problem with some frequencies.

I added F#5 to the tests and it fails 54 clarity tests.
```javascript
                  describe(`of amplitude ${amplitude}`, () => {
                    for (const frequency of [
                      440,
                      880,
                      245,
                      100,
                      440 * 2 ** (9 / 12), 
                    ]) {
```
```
    Expected: > 0.98
    Received:   0.9623680094101329
```

As for frequency, I wrote a `toBeWithinCents` matcher and at 44.1kHz sampling (the buffer size doesn't seem to matter), and it's accurate to within 1 cent for 100 and 245Hz tests, 4 cents for 440 and 880Hz, but at F#5 it's off by -11.7c.  If I change the sampling rate to 48kHz (which is apparently what my Mac defaults to in Chrome), it's -3.6c for 108 tests.

```
expected 738.4615384615385 to be within 3.5 cents of 739.9888454232689Hz (actual -3.5768894038453585)
```

I read the paper and only sort of grok it.  I wonder if the fast algorithm in section 6 implements equation 10 with the symmetry correction.  But I don't understand how `sr/n_peak` is enough to get an accurate pitch.  The error as frequency increases also increases (in a complex way).  Maybe I'm calculating this wrong, but here's the error in cents calculating the pitch this way for piano notes at 44.1k and 48k sampling (my browser does 48k :shrug:).
  
```python
def err(f, sr=44100):
  n = sr//f
  return 1200*math.log2((sr/n)/f)

x = [27.5*2**(n/12) for n in range(0,88)]
y = [err(f, 44100) for f in x]
plt.scatter(x,y)
```
![image](https://user-images.githubusercontent.com/3395020/135733269-6398f91e-041f-4548-8b91-e617bafae847.png)
![image](https://user-images.githubusercontent.com/3395020/135733272-de1ebaaa-3942-45a4-aed8-03f78baa7bf6.png)

I'll reread the paper again tonight and see if I missed something.  Maybe I'll bug the author.

**Comment by ianprime0509** [comment]
Actually, after seeing your calculation of the error, I realized that there's one part of the paper that I didn't implement and [left as a TODO](https://github.com/ianprime0509/pitchy/blob/bb2333b651ebd44ec327953c312de0b08a8383c7/src/index.ts#L152-L154), namely, finding a better approximation for the index of the chosen peak using quadratic interpolation of the found index and its two neighbors (in section 5). Hopefully this will improve the accuracy; I'm not sure why I didn't try implementing it earlier.

**Comment by ianprime0509** [comment]
I made a draft PR for this in #12 (I may go back tomorrow and see if there's anything else I need to improve on), and it seems to improve things; I added tests to check the difference between the actual and expected pitches in cents as well. Thank you for bringing this up! I'm not sure why I didn't try to implement that part earlier, really; I guess it just happened to work well for what I was using it for.

**Comment by ephetic** [comment]
Looks good.  But now the buffer size affects the precision, so should probably update the test to use the default browser fft size (and maybe sampling rate depending on the main platform you envision targeting). 

Android 11
Chrome 94 2048@48000

iOS
TBD

Mac 11.6
Chromium 94: 2048@48000
Safari 15 2048@48000

Windows 10
Chrome 92/94 2048@44100
FireFox 92 2048@44100

**Comment by ianprime0509** [comment]
That's also a good point, thank you! I improved the test suite in #14, by using different combinations of sample rate and window size (and trimming off some of the less important tests, such as most of the tests for buffer types other than `Float32Array`).
