### ISSUE TITLE
error importing with jest

### ISSUE THREAD

**Issue by glend1** [ianprime0509/pitchy#74]
I recently updated to v4 from v3 and now im getting an error with the following line

````
import { PitchDetector } from "pitchy";
````

the error given is; ` SyntaxError: Cannot use import statement outside a module`
and then gives me this line;

````
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import FFT from "fft.js";
````

here is my jest config file;

````
export default {
 
  clearMocks: true,

 
  collectCoverage: true,


  coverageDirectory: "coverage",

 
  coverageProvider: "v8",

 
  moduleNameMapper: {
    /* Handle CSS imports (with CSS modules)
    https://jestjs.io/docs/webpack#mocking-css-modules */
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',

    // Handle CSS imports (without CSS modules)
    '^.+\\.(css|sass|scss)$': '<rootDir>/__mocks__/styleMock.js',

    /* Handle image imports
    https://jestjs.io/docs/webpack#handling-static-assets */
    '^.+\\.(jpg|jpeg|png|gif|webp|avif|svg)$':
      '<rootDir>/__mocks__/fileMock.js',
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
  testEnvironment: 'jsdom',
  transform: {
    /* Use babel-jest to transpile tests with the next/babel preset
    https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object */
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: [
      'next/babel',
      //['@babel/preset-env', {targets: {node: 'current'}}],
      //'@babel/preset-typescript'
    ] }],
  },
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
};
````

**Comment by ianprime0509** [comment]
The primary change (and the only user-visible one) in Pitchy v4 was to make it [ESM-only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), which means that v4 can't be imported using `require` (which, confusingly, is what Babel is transpiling the `import` statement to in your example). There are a few ways to address this:

1. You could try migrating your own project to ES modules. Jest offers [experimental support for ES modules](https://jestjs.io/docs/ecmascript-modules), and there is more information about migration in the [document linked earlier](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
2. If that isn't possible, it is still possible to use a dynamic `import`, but this must be done from an async context:

   ```js
   test("example test", async () => {
     const { PitchDetector } = await import("pitchy");

     // Test logic goes here
   }
   ```

   This will work even in a CommonJS file.
3. You could continue to use Pitchy v3, since, functionally, there is no difference between v3 and v4. If there are any bugs fixed in the future in v4, I will definitely consider backporting the fixes to v3 as well. New features would be a different story, most likely, but I'm also not sure at this time what new features would be added, since the purpose of the library is pretty well-defined and limited (to implement the [McLeod Pitch Method](http://www.cs.otago.ac.nz/tartini/papers/A_Smarter_Way_to_Find_Pitch.pdf)).

As for "why" this change was done, it's primarily a forward-looking approach, seeing as ES modules are "the future", being supported not just in Node.js but in the browser and in new alternatives like [Deno](https://deno.land/), and also supporting nice features like top-level await. But I know a lot of the ecosystem is not quite ready yet, which is where v3 will still be available for those who can't migrate.

**Comment by glend1** [comment]
its weird because `transform` in my `jest.config.js` is handling this fine for all other files...

**Comment by glend1** [comment]
So, I was able to fix this by changing the following to an empty array;

````
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
````
I understand why this worked and that i should ignore `pitchy` for transforming.

But this implies that everyone using `next.js` and `jest` will see this error. I'd rather not add specific libraries to my config like this but if thats what has to be done to ensure we move to ESM only imports i'm behind it. 

Perhaps this should be documented somewhere as a known issue?

**Comment by glend1** [comment]
this is my ending solution.

````
  transformIgnorePatterns: [
    '^.+node_modules\/[^p]*[^i]*[^t]*[^c]*[^h]*[^y]*$',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
````

**Comment by ianprime0509** [comment]
That solution makes sense; by excluding Pitchy from `transformIgnorePatterns`, you're telling Babel to transpile it to CommonJS even though you ordinarily wouldn't want to transpile stuff in `node_modules`. I linked a document with [an overview of ESM-only packages and some solutions for various tools](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) in the README, but it could possibly be more prominent.
